#!/bin/bash

echo "📦 MongoDB Atlas Setup Helper"
echo "=============================="
echo ""
echo "This script will help you set up MongoDB Atlas (free cloud database)"
echo ""
echo "Steps:"
echo "1. Go to: https://www.mongodb.com/cloud/atlas/register"
echo "2. Sign up for free account"
echo "3. Create a FREE cluster (M0 tier)"
echo "4. Create database user (Database Access → Add User)"
echo "5. Whitelist IP (Network Access → Add IP → Add Current IP)"
echo "6. Get connection string (Database → Connect → Connect your application)"
echo ""
echo "Once you have the connection string, run:"
echo ""
echo "  cd backend"
echo "  nano .env"
echo ""
echo "Update MONGODB_URI with your connection string:"
echo "  MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/ai-chatbot"
echo ""
echo "Then restart backend:"
echo "  npm run dev"
echo ""
echo "✅ For detailed instructions, see: MONGODB_FIX.md"
